name: Delete Branch
on:
  push:
    branches:
      - 'develop'

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete branch
        uses: rtCamp/action-delete-branch@v2
        with:
          branch: 'feature/*'
