name: Dependent Workflow
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Manual job
        run: echo "Manual job"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Dependent job
        run: echo "Dependent job"
