name: Fruit-Nom Pipeline
on:
  workflow_dispatch:

jobs:
  generate-phrases:
    strategy:
      matrix:
        fruits: [pomme, bannane, abricot]
        noms: [Pierre, Alexis, Thierry]
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Generate Phrases
        run: |
          for fruit in ${{ matrix.fruits }}; do
            for nom in ${{ matrix.noms }}; do
              echo "${nom} mange une ${fruit}, et il adore ça !"
            done
          done