name: Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests on Node.js 14.x
        run: npm run test

      - name: Generate coverage report
        run: npm run test:coverage
        env:
          CI: true
        if: success()
        run: |
          npm run test:coverage > coverage.txt
          echo "Coverage report generated"
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.txt

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Run tests on Node.js 16.x
        run: npm run test

      - name: Generate coverage report
        run: npm run test:coverage
        env:
          CI: true
        if: success()
        run: |
          npm run test:coverage > coverage.txt
          echo "Coverage report generated"
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.txt
